kind: Service
apiVersion: v1
metadata:
  name: hello-kube-service
  labels:
    app: hello-kube-deployment
spec:
  selector:
    app: hello-kube-pod
  ports:
    - port: 80
      name: http
      targetPort: 3000
  type: LoadBalancer
