apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: 3gppnetwork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-pod
  template:
    metadata:
      labels:
        app: ubuntu-pod
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
  
    
